version: "3.8"

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  json-server:
    image: node:18
    working_dir: /json-server
    volumes:
      - ./data.json:/json-server/db.json
    command: sh -c "npm install -g json-server && json-server --watch db.json --host 0.0.0.0 --port 3000"
    ports:
      - "3001:3000"
